---
title: "Miscellaneous stuff"
author: "Andrew Heiss"
date: "`r format(Sys.time(), '%B %e, %Y')`"
output: 
  html_document: 
    css: ../html/fixes.css
    code_folding: hide
    toc: yes
    toc_float: true
    toc_depth: 4
    highlight: pygments
    theme: cosmo
    self_contained: no
    includes:
      after_body: ../html/add_home_link.html
bibliography: /Users/andrew/Dropbox/Readings/Papers.bib
csl: /Users/andrew/.pandoc/csl/american-political-science-association.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, fig.retina=2,
                      tidy.opts=list(width.cutoff=140),  # For code
                      options(width=140))  # For output

library(tidyverse)
library(haven)
library(forcats)
library(countrycode)
library(rgdal)

source(file.path(PROJHOME, "Analysis", "lib", "graphic_functions.R"))
```

## Global crackdown on civic space (from CIVICUS)

Data downloaded from CIVICUS's [Tableau visualizations online](https://monitor.civicus.org/findings/). See also @CIVICUS:2017.

```{r civicus-crackdown, message=FALSE, warning=FALSE, fig.width=4.5, fig.height=2}
rating.levels <- c("Open", "Narrowed", "Obstructed", "Repressed", "Closed")

# Data from the Tableau visualizations at https://monitor.civicus.org/findings/
civicus <- read_csv(file.path(PROJHOME, "Data", "data_raw", "External", 
                              "CIVICUS", "civicus_monitor_2017.csv"),
                    na="Null") %>%
  mutate(Population = as.double(Population),  # integers can't handle world population
         Rating = factor(Rating, levels=rating.levels, ordered=TRUE),
         iso3 = countrycode(Country, "country.name", "iso3c"))

civicus.population <- civicus %>%
  group_by(Rating) %>%
  summarise(pop.per.rating = sum(Population),
            perc.per.rating = pop.per.rating / sum(civicus$Population))

plot.civicus.population <- ggplot(civicus.population, 
                                  aes(x=perc.per.rating, y=fct_rev(Rating))) + 
  geom_pointrangeh(aes(xmin=0, xmax=perc.per.rating)) +
  labs(x="Percent of world population", y=NULL) +
  scale_x_continuous(labels=scales::percent) +
  theme_ath()
plot.civicus.population

fig.save.cairo(plot.civicus.population, filename="0-civicus-population", 
               width=4.5, height=1.75)
```

```{r civicus-map, fig.width=5.5, fig.height=3}
countries.ggmap <- readRDS(file.path(PROJHOME, "Data", "data_processed",
                                     "countries110_robinson_ggmap.rds"))

countries.to.plot <- countries.ggmap %>% 
  distinct(id) %>%
  left_join(civicus, by = c("id" = "iso3"))

plot.civicus.map <- ggplot(countries.to.plot) +
  geom_map(aes(map_id=id, fill=Rating), map=countries.ggmap, 
           size=0.15, colour="black", alpha=0.8) + 
  expand_limits(x=countries.ggmap$long, y=countries.ggmap$lat) +
  coord_equal() +
  scale_fill_manual(values=c("#2ECC40", "#0074D9", "#B10DC9", "#FF851B", "#FF4136"),
                    breaks=levels(civicus$Rating), na.value = "grey80") +
  guides(fill=guide_legend(title=NULL)) +
  theme_ath_map() + theme(legend.position = "bottom",
                          legend.key.size = unit(0.65, "lines"))
plot.civicus.map

fig.save.cairo(plot.civicus.map, filename="0-civicus-map", 
               width=5.5, height=3)
```

## Goals of government regulation of INGOs and corresponding INGO responses

```{r goals-summary, message=FALSE, results="asis"}
goals <- read_csv(file.path(PROJHOME, "Data", 
                            "data_base", "ingo_reactions_summary.csv")) %>%
  mutate_each(funs(str_replace(., "XXX", "\\\n")))

caption <- "Goals of government regulation of INGOs and corresponding INGO responses {#tbl:ingo-reactions-summary}"
goals.out <- pandoc.table.return(goals, keep.line.breaks=TRUE,
                                 justify="llll", caption=caption, style="grid")

cat(goals.out)
cat(goals.out, file=file.path(PROJHOME, "Output", "tables", 
                              "3-ingo-reactions-summary.md"))
```

## Dictatorships using INGOs with other institutions

```{r ingos-dictatorships, message=FALSE, warning=FALSE}
institutions <- read_stata(file.path(PROJHOME, "Data", "data_raw", "External",
                                     "twq15byyeardta.dta"))

autocrats <- read_stata(file.path(PROJHOME, "Data", "data_raw", "External",
                                     "GWF Autocratic Regimes", "GWFtscs.dta"))

murdie <- read_stata(file.path(PROJHOME, "Data", "data_raw", "External",
                               "Murdie 2014", "11558_2013_9180_MOESM1_ESM.dta")) %>%
  select(year, cowcode, ingos = ingos_1num) %>%
  filter(cowcode %in% autocrats$cowcode) %>%
  mutate(ingos_present = ifelse(ingos > 50, TRUE, FALSE)) %>%
  group_by(year) %>%
  summarize(ingos = sum(ingos_present, na.rm=TRUE) / n()) %>%
  mutate(ingos = ifelse(ingos == 0, NA, ingos))

inst.labels <- c("More than 50 INGOs with members", "At least one party",
                 "Multiple parties and legislature", "Election in last six years")
inst.order <- c("At least one party", "Multiple parties and legislature",
                "Election in last six years", "More than 50 INGOs with members")

plot.data <- institutions %>%
  left_join(murdie, by="year") %>%
  filter(year < 2009 & year > 1950) %>%
  select(year, ingos, percentage_w_party, 
         percentage_partisan_leg, percentage_election_last6) %>%
  gather(variable, value, -year) %>%
  na.omit() %>%
  mutate(variable = factor(variable, labels=inst.labels),
         variable = factor(variable, levels=inst.order, ordered=TRUE))
  
p <- ggplot(plot.data, aes(x=year, y=value, colour=variable)) + 
  geom_hline(yintercept=seq(0.6, 0.9, by=0.1), size=0.25, colour="grey90") + 
  geom_line(size=1) + 
  labs(x=NULL, y="Percentage of dictatorships") + 
  scale_y_continuous(labels=scales::percent) +
  scale_colour_manual(name="", values=ath.palette("palette1")) + 
  guides(colour = guide_legend(nrow=2, byrow=TRUE)) + 
  theme_ath() + theme(legend.key = element_blank())
p

fig.save.cairo(p,
               filename="0-ingos-dictatorships",
               width=4.5, height=3)
```

## References
