---
title: "Article 19 analysis"
author: "Andrew Heiss"
date: "`r format(Sys.time(), '%B %e, %Y')`"
output: 
  html_document: 
    css: ../html/fixes.css
    code_folding: hide
    toc: yes
    toc_float: true
    toc_depth: 4
    highlight: pygments
    theme: cosmo
    self_contained: no
    includes:
      after_body: ../html/add_home_link.html
bibliography: /Users/andrew/Dropbox/Readings/Papers.bib
csl: /Users/andrew/.pandoc/csl/american-political-science-association.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, fig.retina=2,
                      tidy.opts=list(width.cutoff=140),  # For code
                      options(width=140))  # For output

library(tidyverse)
library(forcats)
library(countrycode)
library(rgdal)

source(file.path(PROJHOME, "Analysis", "lib", "graphic_functions.R"))
```

## Budget and staff over time

```{r budget-staff, message=FALSE}
a19.budget <- read_csv(file.path(PROJHOME, "Data", 
                                 "data_base", "a19_budget.csv")) 

a19.budget.long <- a19.budget %>%
  gather(key, value, -Year) %>%
  mutate(type = ifelse(key == "Staff", "Staff", "Budget"))

plot.budget <- ggplot(filter(a19.budget.long, type == "Budget"),
                      aes(x=Year, y=value, colour=key)) +
  geom_line(size=1) +
  labs(x=NULL, y="Reported amount") +
  scale_y_continuous(labels=scales::dollar_format(prefix="£")) +
  scale_color_manual(values=ath.palette("palette1")[3:4], name=NULL) +
  expand_limits(y=0) +
  theme_ath()

plot.staff <- ggplot(filter(a19.budget.long, type == "Staff"),
                     aes(x=Year, y=value)) +
  geom_line(size=1) +
  labs(x=NULL, y="Full time employees") +
  expand_limits(y=0) +
  theme_ath()

plot.both <- rbind(ggplotGrob(plot.budget),
                   ggplotGrob(plot.staff))

panels <- plot.both$layout$t[grep("panel", plot.both$layout$name)]
plot.both$heights[panels] <- unit(c(1, 0.5), "null")

grid::grid.newpage()
grid::grid.draw(plot.both)

fig.save.cairo(plot.both, filename="4-a19-budget-staff", 
               width=4.5, height=3)
```

```{r results="asis"}
a19.budget %>%
  mutate(Surplus = Income - Expenses) %>%
  pander::pandoc.table()
```

Average income per year: `r a19.budget$Income %>% mean() %>% scales::dollar()`


## Regional expenses over time

```{r regional-expenses, message=FALSE}
a19.regional <- read_csv(file.path(PROJHOME, "Data", 
                                 "data_base", "a19_regional_expenses.csv")) %>%
  filter(!(Category %in% c("Governance", "Fundraising", "Law and policy"))) %>%
  mutate(Category = ordered(fct_relevel(Category, "Global"))) %>%
  group_by(Year, Category) %>%
  summarise(Amount = sum(Amount))

plot.regions <- ggplot(a19.regional, aes(x=Year, y=Amount)) +
  geom_line(size=1) +
  labs(x=NULL, y="Reported expenditures") +
  scale_y_continuous(labels=scales::dollar_format(prefix="£")) +
  scale_color_manual(values=ath.palette("palette1"), guide=FALSE) +
  theme_ath() + theme(strip.text=element_text(size=rel(0.8)),
                      strip.background=element_rect(fill="grey90")) +
  facet_wrap(~ Category)
plot.regions


a19.percent <- a19.regional %>%
  group_by(Year) %>%
  mutate(total = sum(Amount),
         percent = Amount / total)

plot.percent <- ggplot(a19.percent, aes(x=Year, y=percent)) +
  geom_line(size=1) +
  labs(x=NULL, y="Percent spent on region") +
  scale_y_continuous(labels=scales::percent) +
  scale_color_manual(values=ath.palette("palette1"), guide=FALSE) +
  theme_ath() + theme(strip.text=element_text(size=rel(0.8)),
                      strip.background=element_rect(fill="grey90")) +
  facet_wrap(~ Category)
plot.percent

fig.save.cairo(plot.regions, filename="4-a19-regions-expenses-abs", 
               width=5.5, height=2.5)

fig.save.cairo(plot.percent, filename="4-a19-regions-expenses-pct", 
               width=5.5, height=2.5)
```

## Regional offices

```{r regional-offices, message=FALSE, warning=FALSE}
# Load Robinson map projection
countries.ggmap <- readRDS(file.path(PROJHOME, "Data", "data_processed",
                                     "countries110_robinson_ggmap.rds"))

# All possible countries (to fix the South Sudan issue)
possible.countries <- data_frame(id = unique(as.character(countries.ggmap$id)))

# Convert office city coordinates to Robinson projection
a19.offices <- read_csv(file.path(PROJHOME, "Data", 
                                 "data_base", "a19_offices.csv")) %>%
  mutate(iso = countrycode(country, "country.name", "iso3c"))

offices.robinson <- project(as.matrix(a19.offices %>% select(long, lat)), 
                              proj="+proj=robin") %>%
  as.data.frame %>% rename(long.robinson = long, lat.robinson = lat)

offices.to.plot <- bind_cols(a19.offices, as.data.frame(offices.robinson))

plot.offices <- ggplot(possible.countries) +
  geom_map(aes(map_id=id), map=countries.ggmap, 
           size=0.15, colour="black", fill="grey90") + 
  geom_point(data=offices.to.plot, 
             aes(x=long.robinson, y=lat.robinson, 
                 fill=NULL), 
             colour="black", size=1.5) + 
  geom_label_repel(data=offices.to.plot,
                   aes(x=long.robinson, y=lat.robinson, 
                       label=office, fill=hq),
                   size=3) +
  expand_limits(x=countries.ggmap$long, y=countries.ggmap$lat) + 
  coord_equal() +
  scale_fill_manual(values=c("#FFDC00", "#FF851B"), guide=FALSE) +
  scale_colour_manual(values=c("#FFDC00", "#FF851B"), guide=FALSE) +
  theme_ath_map()
plot.offices

fig.save.cairo(plot.offices, filename="4-a19-offices", 
               width=5.5, height=2.5)
```

## Reports in the Middle East

Middle Eastern countries where Article 19 has issues 10+ reports between 2011 and 2017, based on counts from June 19, 2017 at the [Resources database](https://www.article19.org/resources.php?action=resourcesearch&search=test&lang=en).

```{r me-reports, message=FALSE, fig.width=4.5, fig.height=2}
a19.me <- read_csv(file.path(PROJHOME, "Data", 
                             "data_base", "a19_me_reports.csv"))  %>%
  arrange(reports) %>%
  mutate(country = fct_inorder(country))

plot.me.reports <- ggplot(a19.me, aes(x=reports, y=country, colour=hq)) + 
  geom_pointrangeh(aes(xmin=0, xmax=reports)) +
  labs(x="Advocacy letters, reports, statements, and updates", y=NULL) +
  scale_colour_manual(values=c("grey30", "#FF851B"), guide=FALSE) +
  theme_ath() + theme(panel.grid.major.y=element_blank())
plot.me.reports

fig.save.cairo(plot.me.reports, filename="4-a19-me-reports", 
               width=4.5, height=2)
```

