---
title: "Index on Censorship analysis"
author: "Andrew Heiss"
date: "`r format(Sys.time(), '%B %e, %Y')`"
output: 
  html_document: 
    css: ../html/fixes.css
    code_folding: hide
    toc: yes
    toc_float: true
    toc_depth: 4
    highlight: pygments
    theme: cosmo
    self_contained: no
    includes:
      after_body: ../html/add_home_link.html
bibliography: /Users/andrew/Dropbox/Readings/Papers.bib
csl: /Users/andrew/.pandoc/csl/american-political-science-association.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, fig.retina=2,
                      tidy.opts=list(width.cutoff=140),  # For code
                      options(width=140))  # For output

library(tidyverse)
library(jsonlite)
library(lubridate)
library(countrycode)
library(rgdal)

source(file.path(PROJHOME, "Analysis", "lib", "graphic_functions.R"))
```

## Budget and staff over time

```{r budget-staff, message=FALSE}
# Yay opencharities.org!
# http://opencharities.org/charities/325003/accounts
# Get JSON with their API: http://opencharities.org/charities/325003.json
index.budget.raw <- fromJSON(file.path(PROJHOME, "Data", 
                                       "data_base", "index_budget.json"))

index.budget <- index.budget.raw$charity$annual_reports %>%
  mutate(Year = year(financial_year_end)) %>%
  select(Year, Income = total_income, Expenses = total_expenses, Staff = employees)

index.budget.long <- index.budget %>%
  gather(key, value, -Year) %>%
  mutate(type = ifelse(key == "Staff", "Staff", "Budget"))

plot.budget <- ggplot(filter(index.budget.long, type == "Budget"),
                      aes(x=Year, y=value, colour=key)) +
  geom_line(size=1) +
  labs(x=NULL, y="Reported amount") +
  # Automatic y-axis scaling to 0!
  scale_y_continuous(labels=scales::dollar_format(prefix="£"),
                     limits=c(0, NA)) +
  scale_color_manual(values=ath.palette("palette1")[3:4], name=NULL) +
  theme_ath()

plot.staff <- ggplot(filter(index.budget.long, type == "Staff"),
                     aes(x=Year, y=value)) +
  geom_line(size=1) +
  labs(x=NULL, y="Full time employees") +
  # Automatic y-axis scaling to 0!
  expand_limits(y=0) +
  theme_ath()

plot.both <- rbind(ggplotGrob(plot.budget),
                   ggplotGrob(plot.staff))

panels <- plot.both$layout$t[grep("panel", plot.both$layout$name)]
plot.both$heights[panels] <- unit(c(1, 0.5), "null")

grid::grid.newpage()
grid::grid.draw(plot.both)

fig.save.cairo(plot.both, filename="5-index-budget-staff", 
               width=4.5, height=3)
```

```{r results="asis"}
index.budget %>%
  mutate(Surplus = Income - Expenses) %>%
  pander::pandoc.table()
```

Average income per year: `r index.budget$Income %>% mean() %>% scales::dollar()`

## Awards and fellowships

```{r awards-fellowships, message=FALSE, warning=FALSE}
# Load Robinson map projection
countries.ggmap <- readRDS(file.path(PROJHOME, "Data", "data_processed",
                                     "countries110_robinson_ggmap.rds"))

possible.countries <- data_frame(id = unique(as.character(countries.ggmap$id)))

# via http://techslides.com/list-of-countries-and-capitals
countries.geocoded <- read_csv(file.path(PROJHOME, "Data", "data_raw",
                                         "External", "country-capitals.csv")) %>%
  mutate(iso3 = countrycode(CountryName, "country.name", "iso3c")) %>%
  select(iso3, lat = CapitalLatitude, long = CapitalLongitude)

index.awards <- read_csv(file.path(PROJHOME, "Data", 
                                   "data_base", "index_awards.csv")) %>%
  mutate(iso3 = countrycode(`Home country`, "country.name", "iso3c")) %>%
  left_join(countries.geocoded, by="iso3")
  
# Conver coordinates to Robinson projection
awards.robinson <- project(as.matrix(index.awards %>% select(long, lat)), 
                           proj="+proj=robin") %>%
  as.data.frame %>% rename(long.robinson = long, lat.robinson = lat)

# Count number of times a country gets an award
awards.aggregated <- bind_cols(index.awards, as.data.frame(awards.robinson)) %>%
  count(iso3, lat, long, long.robinson, lat.robinson) %>%
  filter(!is.na(iso3))

awards.individual <- bind_cols(index.awards, as.data.frame(awards.robinson)) %>%
  filter(!is.na(iso3))

# Load country-level autocracy data
autocracies <- readRDS(file.path(PROJHOME, "Data", "data_processed",
                                 "autocracies.rds"))

countries.to.plot <- possible.countries %>%
  left_join(awards.aggregated, by=c("id" = "iso3")) %>%
  replace_na(list(n = 0)) %>%
  mutate(presence = n > 0,
         autocracy = id %in% unique(autocracies$iso3)) %>%
  mutate(autocracy.presence = case_when(
           .$presence & .$autocracy ~ "Autocracy",
           .$presence & !.$autocracy ~ "Non-autocracy",
           TRUE ~ "No recipients"
         )) %>%
  mutate(autocracy.presence = factor(autocracy.presence, 
                                     levels=c("Autocracy", "Non-autocracy", "No recipients"),
                                     ordered=TRUE))

plot.awards <- ggplot(countries.to.plot) +
  geom_map(aes(map_id=id, fill=autocracy.presence), map=countries.ggmap, 
           size=0.15, colour="black") + 
  geom_point(data=awards.aggregated, 
             aes(x=long.robinson, y=lat.robinson, size=n), 
             colour="black") + 
  expand_limits(x=countries.ggmap$long, y=countries.ggmap$lat) +
  coord_equal() +
  scale_fill_manual(values=c("#FF4136", "grey50", "white")) +
  scale_radius(range=c(0.5, 3.5)) +
  guides(size=guide_legend(nrow=1, order=0, title="Number of award recipients:"),
         fill=guide_legend(order=1, title=NULL)) +
  theme_ath_map() + theme(legend.position="bottom",
                          legend.key.size=unit(0.65, "lines"))
plot.awards

fig.save.cairo(plot.awards, filename="5-index-awards", 
               width=5.5, height=3)
```

Unique countries:

```{r}
awards.aggregated %>% nrow()
```

Number of recipients:

```{r}
awards.individual %>% nrow()
```
