---
title: "Dissertation analysis"
author: "Andrew Heiss"
date: "`r format(Sys.time(), '%B %e, %Y')`"
output: 
  html_document: 
    css: html/fixes.css
    highlight: pygments
    theme: cosmo
---

## Chapters

1. [The Strategic Balance between Dictators and International NGOs](Writing/0_introduction/introduction.html)
2. [Authoritarian Institutions and Restrictions on International Civil Society](Writing/1_cs_regime_stability/cs_regime_stability.html)
3. [International NGO restrictions in the Middle East, Eastern Europe, and East Asia](Writing/2_country_case_studies/country_case_studies.html)
4. ["We changed our strategy… without losing our values, vision and mission": Mission, money, and the practical operating environment](Writing/3_ingo_mechanisms/ingo_mechanisms.html)
5. ["They do not want us to operate there": INGO responses to gatekeeping regulations](Writing/4_gatekeeping/gatekeeping.html)
6. ["Some state officials want your services": INGO responses to program capture regulations](Writing/5_program_capture/program_capture.html)
7. [Conclusion](Writing/6_conclusion/conclusion.html)


## Civil society regulatory environment in authoritarian regimes

- [Non-regression analysis](ngo_regs_regime_stability/misc_analysis.html)
- [Models](ngo_regs_regime_stability/models.html)

## Case studies of international aspect of CSRE

- [LNA-based case selection](country_case_studies/case_selection.html)
- [Case study timelines](country_case_studies/timelines.html)

## INGO survey

- [Completion rates](ingo_survey/completion_rates.html)
- [Summary](ingo_survey/survey_summary.html)
- [Analysis](ingo_survey/survey_analysis.html)
- [Actual analysis](ingo_survey/actual_analysis.html)

## Case studies of INGOs

- [Article 19](ingo_case_studies/article_19.html)
- [AMERA UK/Egypt/International](ingo_case_studies/amera.html)
- [Index on Censorship](ingo_case_studies/index_censorship.html)
- [IRI](ingo_case_studies/iri.html)

## Miscellaneous stuff

- [Miscellaneous analysis](misc/misc_analysis.html)
